services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: hfa
      POSTGRES_PASSWORD: changeinprod


  #Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080